version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: phpdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"